---
version: '3.7'
services:
  # Service image
  app:
    image: pipenv-all:latest
    build:
      context: app
      args:
        PYTHONVERS: $PYTHONVERS
    volumes:
      - type: bind
        source: .
        target: /workspace
